
module.exports = {		
		staticStyles:[
		              'app/assets/plugins/loader.css',
		              'app/assets/plugins/font-awesome/css/font-awesome.css',
		              'app/assets/plugins/summernote/css/summernote.css',
		              'app/assets/plugins/simple-line-icons/dist/simple-line-icons.css',
		              'app/vendor/bootstrap/dist/css/bootstrap.css',
		              'app/vendor/AngularJS-Toaster/toaster.css',
		              'app/vendor/angular-block-ui/dist/angular-block-ui.css',
		              'app/assets/global/css/bootstrap-datetimepicker.css',
		              'app/src/global.css',
		              'app/assets/plugins/jquery-ui.css',
		              'app/assets/plugins/float.css', 
		              'app/assets/global/css/components-rounded.css',
		              'app/assets/global/css/plugins.css',
		              'app/assets/layouts/layout4/css/layout.css',
		              'app/assets/layouts/layout4/css/themes/default.css',
		              'app/assets/layouts/layout4/css/themes/darkblue.css',
		              'app/assets/layouts/layout4/css/custom.css',
		              'app/assets/global/css/bootstrap-xlg.css',
		              'app/vendor/ng-duallist/ngduallist.css',
		              'app/assets/plugins/intlTelInput.css'
		              ],
		 dynamicStyles:[
		                'app/assets/plugins/bootstrap-float-label/dist/bootstrap-float-label.css',
		                'app/src/main/audit/audit.css',
		                'app/src/main/login/login.css',
		                'app/src/main/dashboard/dashboard.css',
		                'app/src/main/Master Maintenance/master.css',
		                'app/src/main/userSearch/userSearch.css',
		                'app/src/main/centralLog/centralLog.css',
		                'app/src/main/vesselStatement/vesselStatement.css',
		                'app/src/main/config/config.css',
                      	'app/assets/plugins/jquery.dataTables.css',
                    	'app/assets/plugins/angular-datatables.css',
                    	'app/vendor/datatables.net-responsive-dt/css/responsive.dataTables.css',
                    	'app/vendor/datatables.net-select-dt/css/select.dataTables.css',
                    	'app/src/mozGlobal.css'
		                ],
      dynamicColorStyle:[
                         'app/src/dynamicColorChange.css'
                         ],             
		  htmlPages:[
		             'app/src/template/template.html',
		             'app/src/main/login/login.html',
		             'app/src/main/audit/ism/ism.html',
		             'app/src/main/audit/ssp/ssp.html',
		             'app/src/main/audit/isps/isps.html',
		             'app/src/main/audit/mlc/mlc.html',
		             'app/src/Modals/auditorDetail.html',
		             'app/src/Modals/findingPreview.html',
		             'app/src/Modals/reportattachment.html',
		             'app/src/Modals/reportPreview.html',
		             'app/src/main/audit/search/search.html',
		             'app/src/main/support/support.html',
		             'app/src/main/support/supportSearch/supportSearch.html'
		             ],
	  vendorScripts :[
	                  
		            'app/assets/plugins/jquery.min.js',
		            'app/assets/plugins/jquery.easing.min.js',
		            'app/vendor/jquery-ui/ui/jquery-1-7.js',
		            'app/vendor/jquery-ui/jquery-ui.js',
		            'app/vendor/bootstrap/dist/js/bootstrap.js',
		            'app/vendor/bootstrap-hover-dropdown/bootstrap-hover-dropdown.js',
		            'app/vendor/datatables/media/js/jquery.dataTables.js',
		            'app/vendor/datatables.net/js/jquery.dataTables.js',
		            'app/vendor/datatables.net-buttons/js/dataTables.buttons.js',
		            'app/vendor/datatables.net-buttons-bs/js/buttons.bootstrap.js',
		            'app/vendor/datatables.net-buttons-jqui/js/buttons.jqueryui.js',
		            'app/vendor/datatables.net-buttons/js/buttons.colVis.js',
		            'app/vendor/datatables.net-responsive/js/dataTables.responsive.js',
		            'app/assets/plugins/moment.js',
		            'app/assets/plugins/bootstrap-datetimepicker.js',
		            'app/vendor/angular/angular.js',
		            'app/assets/plugins/angular.ngcss.min.js',
		            'app/vendor/ngCapsLock/ng-caps-lock.min.js',
		            'app/vendor/angular-datatables/dist/angular-datatables.js',
		            'app/vendor/angular-datatables/dist/plugins/buttons/angular-datatables.buttons.js',
		            'app/assets/plugins/ngduallist.js',
		            'app/assets/plugins/angular-touch.min.js',
		            'app/vendor/angular-ui-router/release/angular-ui-router.js',
		            'app/vendor/oclazyload/dist/ocLazyLoad.js',
		          	'app/assets/plugins/ui-bootstrap-tpls.js',
		         	'app/assets/plugins/ngStorage/ngStorage.min.js',
		         	'app/assets/plugins/toaster.js',
		         	'app/assets/plugins/jspdf/dist/jspdf.min.js',
		         	'app/assets/plugins/jspdf/dist/jspdf.debug.js',
		         	'app/vendor/angular-cookies/angular-cookies.js',
		         	'app/vendor/angular-animate/angular-animate.js',
		         	'app/vendor/angular-modal-service/dst/angular-modal-service.js',
		         	'app/vendor/angular-strap/dist/angular-strap.js',
		         	'app/vendor/angular-resource/angular-resource.js',
		         	'app/vendor/moment/moment.js',
		         	'app/vendor/angular-moment/angular-moment.js',
		         	'app/vendor/angular-local-storage/dist/angular-local-storage.js',
		         	'app/vendor/lodash/dist/lodash.js',
		         	'app/vendor/underscore/underscore-min.js',
		         	'app/vendor/angular-block-ui/dist/angular-block-ui.js',
		         	'app/assets/plugins/rasterizeHTML.allinone.js',
		         	'app/assets/plugins/summernote/summernote.js',
		            'app/vendor/angular-summernote/dist/angular-summernote.min.js',
		            'app/assets/plugins/intlTelInput.js',
		            'app/vendor/intl-tel-input/build/js/utils.js',
		            'app/vendor/ng-intl-tel-input/dist/ng-intl-tel-input.js',
		            'app/vendor/ng-intl-tel-input/ng-intl-tel-input.module.js',
		            'app/vendor/ng-intl-tel-input/ng-intl-tel-input.provider.js',
		            'app/assets/plugins/ng-intl-tel-input.directive.js',
		            'app/assets/plugins/ng-backstretch.js',
					'app/assets/global/scripts/app.js',
					'app/assets/layouts/layout4/scripts/layout.js',
					'app/assets/layouts/global/scripts/quick-sidebar.js',
					'app/assets/layouts/layout4/scripts/demo.js',
					'app/vendor/sockjs-client/dist/sockjs.min.js',
					'app/vendor/stomp-websocket/lib/stomp.min.js',
					'app/vendor/ng-stomp/dist/ng-stomp.min.js',
					'app/assets/plugins/pdfmake/build/pdfmake.js',
					'app/assets/plugins/pdfmake/build/vfs_fonts.js',
	                'app/assets/plugins/polyfill.js',
	                'app/vendor/qrcode/lib/qrcode.min.js',
	                'app/vendor/angular-qr/angular-qr.min.js',
					
		         	],
		AppScripts :[
		             'app/src/core/core.module.js',
		             'app/src/template/template.module.js',
		             'app/src/template/template.controller.js',
		             'app/src/main/auditCycle/auditCycle.module.js',
		             'app/src/main/auditCycle/auditCycle.route.js',
		             'app/src/main/auditCycle/auditCycle.controller.js',
		             'app/src/main/auditCycle/auditCycle.factory.js',
		             'app/src/main/auditCycle/auditCycle.api.js',
		             'app/src/main/certificateViewer/certificateViewer.module.js',
		             'app/src/main/certificateViewer/certificateViewer.route.js',
		             'app/src/main/certificateViewer/certificateViewer.controller.js',
		             'app/src/main/certificateViewer/certificateViewer.factory.js',
		             'app/src/main/certificateViewer/certificateViewer.api.js',
		             'app/src/main/audit/audit.module.js',
		             'app/src/main/audit/audit.route.js',
		             'app/src/main/audit/audit.controller.js',
		             'app/src/main/audit/audit.factory.js',
		             'app/src/main/audit/audit.services.js',
		             'app/src/main/audit/audit.api.js',
		             'app/src/main/audit/audit.common.js',
		             'app/src/main/audit/images.js',
		             'app/src/main/auditCycle/auditCycle.module.js',
		             'app/src/main/auditCycle/auditCycle.route.js',
		             'app/src/main/auditCycle/auditCycle.controller.js',
		             'app/src/main/auditCycle/auditCycle.factory.js',
		             'app/src/main/auditCycle/auditCycle.api.js',
		             'app/src/main/audit/search/search.module.js',
		             'app/src/main/audit/search/search.route.js',
		             'app/src/main/audit/search/search.controller.js',
		             'app/src/main/audit/details/details.module.js',
		             'app/src/main/audit/details/details.route.js',
					 'app/src/main/audit/details/details.controller.js',
					 'app/src/main/audit/details/details.factory.js',
					 'app/src/main/audit/details/details.api.js',
					 'app/src/main/audit/detailsIhm/detailsIhm.module.js',
			         'app/src/main/audit/detailsIhm/detailsIhm.route.js', 
					 'app/src/main/audit/detailsIhm/detailsIhm.controller.js',
					 'app/src/main/audit/detailsIhm/detailsIhm.factory.js',
					 'app/src/main/audit/detailsIhm/detailsIhm.api.js',
					 'app/src/main/audit/detailsPlanApproval/detailsPlanApproval.module.js',
			         'app/src/main/audit/detailsPlanApproval/detailsPlanApproval.route.js', 
					 'app/src/main/audit/detailsPlanApproval/detailsPlanApproval.controller.js',
					 'app/src/main/audit/detailsPlanApproval/detailsPlanApproval.factory.js',
					 'app/src/main/audit/detailsPlanApproval/detailsPlanApproval.api.js',
		             'app/src/main/audit/findings/findings.module.js',
		             'app/src/main/audit/findings/findings.route.js',
					 'app/src/main/audit/findings/findings.controller.js',
					 'app/src/main/audit/findings/findings.factory.js',
					 'app/src/main/audit/findings/findings.api.js',
					 'app/src/main/audit/dmlcFindings/dmlcFindings.module.js',
		             'app/src/main/audit/dmlcFindings/dmlcFindings.route.js',
					 'app/src/main/audit/dmlcFindings/dmlcFindings.controller.js',
					 'app/src/main/audit/dmlcFindings/dmlcFindings.factory.js',
					 'app/src/main/audit/dmlcFindings/dmlcFindings.api.js',
		             'app/src/main/audit/prevFindings/prevFindings.module.js',
		             'app/src/main/audit/prevFindings/prevFindings.route.js',
					 'app/src/main/audit/prevFindings/prevFindings.controller.js',
					 'app/src/main/audit/prevFindings/prevFindings.factory.js',
					 'app/src/main/audit/prevFindings/prevFindings.api.js',
		             'app/src/main/vesselStatement/vesselStatement.module.js',
		         	 'app/src/main/vesselStatement/vesselStatement.route.js',
		         	 'app/src/main/vesselStatement/vesselStatement.controller.js',
		         	 'app/src/main/vesselStatement/vesselStatement.factory.js',
		         	 'app/src/main/vesselStatement/vesselStatement.api.js',
		         	 'app/src/main/certificate/certDetails/certDetails.module.js',
		         	 'app/src/main/certificate/certDetails/certDetails.route.js',
		         	 'app/src/main/certificate/certDetails/certDetails.controller.js',
		         	 'app/src/main/certificate/certDetails/certDetails.service.js',
		         	
		         	'app/src/main/certificate/certDetailsIHM/certDetailsIHM.module.js',
		         	 'app/src/main/certificate/certDetailsIHM/certDetailsIHM.route.js',
		         	 'app/src/main/certificate/certDetailsIHM/certDetailsIHM.controller.js',
		         	 
		         	'app/src/main/certificate/certDetailsIHMExe/certDetailsIHMExe.module.js',
		         	 'app/src/main/certificate/certDetailsIHMExe/certDetailsIHMExe.route.js',
		         	 'app/src/main/certificate/certDetailsIHMExe/certDetailsIHMExe.controller.js',
		         	
		         	 'app/src/main/certificate/certGenerate/certGenerate.module.js',
		         	 'app/src/main/certificate/certGenerate/certGenerate.route.js',
		         	 'app/src/main/certificate/certGenerate/certGenerate.controller.js',
		         	 
		         	 'app/src/main/certificate/certSearch/certSearch.module.js',
		         	 'app/src/main/certificate/certSearch/certSearch.route.js',
		         	 'app/src/main/certificate/certSearch/certSearch.controller.js',
		         	 'app/src/main/certificate/certificate.module.js',
		         	 'app/src/main/certificate/certificate.route.js',
		         	 'app/src/main/certificate/certificate.controller.js',
		         	 'app/src/main/certificate/certificate.factory.js',
		         	 'app/src/main/certificate/certificate.api.js',
		         	 'app/src/main/carMaintenance/carDetails/carDetails.module.js',
		         	 'app/src/main/carMaintenance/carDetails/carDetails.route.js',
		         	 'app/src/main/carMaintenance/carDetails/carDetails.controller.js',
		         	 'app/src/main/carMaintenance/carSearch/carSearch.module.js',
		         	 'app/src/main/carMaintenance/carSearch/carSearch.route.js',
		          	 'app/src/main/carMaintenance/carSearch/carSearch.controller.js',
		          	 'app/src/main/carMaintenance/carMaintenance.module.js',
		          	 'app/src/main/carMaintenance/carMaintenance.route.js',
		          	 'app/src/main/carMaintenance/carMaintenance.controller.js',
		          	 'app/src/main/carMaintenance/carMaintenance.factory.js',
		          	 'app/src/main/carMaintenance/carMaintenance.api.js',
		          	 'app/src/main/dashboard/dashboard.module.js',
		          	 'app/src/main/dashboard/dashboard.route.js',
		          	 'app/src/main/dashboard/dashboard.controller.js',
		             'app/vendor/js-sha256/src/sha256.js',
		             'app/src/main/login/login.module.js',
		             'app/src/main/login/login.route.js',
		             'app/src/main/login/login.controller.js',
		             'app/src/main/config/config.module.js',
		             'app/src/main/config/config.route.js',
		             'app/src/main/config/config.controller.js',
		            'app/src/main/userSearch/userSearch.module.js',
		             'app/src/main/userSearch/userSearch.route.js',
		             'app/src/main/userSearch/userSearch.controller.js',
		             'app/src/main/userSearch/userSearch.factory.js',
		             'app/src/main/userSearch/userSearch.api.js',
		             'app/src/main/centralLog/centralLog.module.js',
		             'app/src/main/centralLog/centralLog.route.js',
		             'app/src/main/centralLog/centralLog.controller.js',
		             'app/src/main/centralLog/centralLog.factory.js',
		             'app/src/main/centralLog/centralLog.api.js',
		             'app/src/main/Master Maintenance/master.module.js',
		             'app/src/main/Master Maintenance/master.route.js',
		             'app/src/main/Master Maintenance/master.controller.js',
		             'app/src/main/Master Maintenance/master.factory.js',
		             'app/src/main/Master Maintenance/master.api.js',
		             'app/src/main/support/support.module.js',
			         'app/src/main/support/support.route.js',
			         'app/src/main/support/support.controller.js',
			         'app/src/main/support/support.factory.js',
			         'app/src/main/support/support.api.js',
			         'app/src/main/support/supportSearch/supportSearch.module.js',
			         'app/src/main/support/supportSearch/supportSearch.route.js',
			         'app/src/main/support/supportSearch/supportSearch.controller.js',
			         'app/src/main/Master Maintenance/user/user.module.js',
		             'app/src/main/Master Maintenance/user/user.route.js',
		             'app/src/main/Master Maintenance/user/user.controller.js',
		             'app/src/main/Master Maintenance/user/user.factory.js',
		             'app/src/main/Master Maintenance/user/user.api.js',
		             'app/src/main/Master Maintenance/vesselDetails/vesselDetails.module.js',
		             'app/src/main/Master Maintenance/vesselDetails/vesselDetails.route.js',
		             'app/src/main/Master Maintenance/vesselDetails/vesselDetails.controller.js',
		             'app/src/main/Master Maintenance/vesselDetails/vesselDetails.factory.js',
		             'app/src/main/Master Maintenance/vesselDetails/vesselDetails.api.js',
		             'app/src/main/Master Maintenance/vesselCompanyDetails/vesselCompanyDetails.module.js',
		             'app/src/main/Master Maintenance/vesselCompanyDetails/vesselCompanyDetails.route.js',
		             'app/src/main/Master Maintenance/vesselCompanyDetails/vesselCompanyDetails.controller.js',
		             'app/src/main/Master Maintenance/vesselCompanyDetails/vesselCompanyDetails.factory.js',
		             'app/src/main/Master Maintenance/vesselCompanyDetails/vesselCompanyDetails.api.js',
		             'app/src/main/Master Maintenance/auditCode/auditCode.module.js',
		             'app/src/main/Master Maintenance/auditCode/auditCode.route.js',
		             'app/src/main/Master Maintenance/auditCode/auditCode.controller.js',
		             'app/src/main/Master Maintenance/auditCode/auditCode.factory.js',
		             'app/src/main/Master Maintenance/auditCode/auditCode.api.js',
		             
		             'app/src/main/Master Maintenance/portDetails/portDetails.module.js',
		             'app/src/main/Master Maintenance/portDetails/portDetails.route.js',
		             'app/src/main/Master Maintenance/portDetails/portDetails.controller.js',
		             'app/src/main/Master Maintenance/portDetails/portDetails.factory.js',
		             'app/src/main/Master Maintenance/portDetails/portDetails.api.js',
		             
		             'app/src/main/Master Maintenance/report/report.module.js',
		             'app/src/main/Master Maintenance/report/report.route.js',
		             'app/src/main/Master Maintenance/report/report.controller.js',
		             'app/src/main/Master Maintenance/report/report.factory.js',
		             'app/src/main/Master Maintenance/report/report.api.js',
		             
		             
		             'app/src/main/Master Maintenance/ihm_ExemptionDetails/ihm_ExemptionDetails.module.js',
		             'app/src/main/Master Maintenance/ihm_ExemptionDetails/ihm_ExemptionDetails.route.js',
		             'app/src/main/Master Maintenance/ihm_ExemptionDetails/ihm_ExemptionDetails.controller.js',
		             'app/src/main/Master Maintenance/ihm_ExemptionDetails/ihm_ExemptionDetails.factory.js',
		             'app/src/main/Master Maintenance/ihm_ExemptionDetails/ihm_ExemptionDetails.api.js',
		             
		             
		             'app/src/app.module.js',
		             'app/src/app.config.js',
		             'app/src/app.factory.js',
		             'app/src/app.constants.js',
		             'app/src/app.controller.js',
		             'app/src/app.route.js',
		             'app/src/app.service.js',
		             'app/src/app.run.js',
		             'app/src/app.directives.js',
		             'app/src/app.api.js',
		             
		             
		             'app/src/main/vesselHistory/vesselHistory.module.js',
		         	 'app/src/main/vesselHistory/vesselHistory.route.js',
		         	 'app/src/main/vesselHistory/vesselHistory.controller.js',
		         	 'app/src/main/vesselHistory/vesselHistory.api.js'
		         	 
		           ],             
	  //Unprotected urls & resources
	  unprotected : [
	                 /\/*.js/,
	                 /\/*.css/,
	                 /\/*.ico/,
	                 /\/*.png/,
	                 /\/*.gif/,
	                 /\/*.woff/,
	                 /\/*.woff2/,
	                 /\/*.tiff/,
	                 /\/*.mp4/,
	                 /\/*.webm/,
	                 /\/*.json/,
	                 /\/*.html/,
	                 /^\/app\/login\/*/,
	                 /^\/app\/logout\/*/,
	                 '/',
	                 '/api/getAvailUsers',
	                 '/refresh',
	                 ]
};